aliases: []
creation_timestamp: 1774445594508
current_stage: None
description: null
last_updated_timestamp: 1774445594508
name: SVM_Telecom
run_id: b431a894ba264f7b8709d151dbd71ff3
run_link: null
source: file:///D:/chatbot_telecom/datasets/modele_scratch/mlflow_logs/146584807365788300/b431a894ba264f7b8709d151dbd71ff3/artifacts/svm_model
status: READY
status_message: null
storage_location: file:///D:/chatbot_telecom/datasets/modele_scratch/mlflow_logs/146584807365788300/b431a894ba264f7b8709d151dbd71ff3/artifacts/svm_model
user_id: null
version: 2
