aliases: []
creation_timestamp: 1774712109447
current_stage: None
description: null
last_updated_timestamp: 1774712109447
name: SVM_Telecom
run_id: 2a810635179d42f49b8f2e81d3a27808
run_link: null
source: file:///D:/chatbot_telecom/datasets/modele_scratch/mlflow_logs/266140618041837205/2a810635179d42f49b8f2e81d3a27808/artifacts/svm_model
status: READY
status_message: null
storage_location: file:///D:/chatbot_telecom/datasets/modele_scratch/mlflow_logs/266140618041837205/2a810635179d42f49b8f2e81d3a27808/artifacts/svm_model
user_id: null
version: 1
